version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running pre-build checks..."


      - echo "Fetching secrets and writing to .env in the project directory"
      - |
        aws secretsmanager get-secret-value --secret-id prod/strikem \
        --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' > $CODEBUILD_SRC_DIR/.env

      - echo ".env file created:"
      - cat $CODEBUILD_SRC_DIR/.env

  build:
    commands: 

      - echo "Running Tests"

      - pytest -v


      - echo "Checking if FastAPI app runs without errors..."
      - |
        python -m uvicorn app.main:app --host 127.0.0.1 --port 8000 &
        APP_PID=$!
        echo "Waiting a few seconds to verify FastAPI starts successfully..."
        sleep 5
        if ps -p $APP_PID > /dev/null
        then
          echo "FastAPI app started successfully!"
          kill $APP_PID
        else
          echo "FastAPI app failed to start."
          exit 1
        fi

artifacts:
  files:
    - '**/*'
