name: Zip and Upload to S3

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  zip_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_S3_REGION_NAME }}

    - name: Zip project files
      run: |
        zip -r project.zip .  

    - name: Upload ZIP file to S3
      run: |
        aws s3 cp project.zip s3://logiks-artifacts/logiks/project.zip